algoritmo "CMD-Enquanto3"
// Autor : Ana Amélia Espíndola de Araújo
// Data : 28/05/2019
// Seção de Declarações 
var ES:Caracter
  N1,N2,N3,M:Real

inicio
 Enquanto (ES <> "N") faca
  escreva ("digite a primeira nota:")
  leia(n1)
  escreva ("digite a segunda nota:")
  leia (n2)
  escreva ("digite a terceira nota:")
  leia (n3)
  m<-(n1+n2+n3)/3
  Escreval("A soma:",M)
  Escreval ("Continua S/N:")
  Leia (ES)
  Fimenquanto
fimalgoritmo
