Algoritmo "CMD-Repita2"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Rodrigo Piantino
// Autor(a)    : Ana Amélia Espíndola de Araújo
// Data atual  : 31/05/2019
Var VT,Q,P,S1,s2: Real
Inicio

Repita
Escreva ("Digite a quantidade de itens:")
Leia (Q)
S1<-S1+Q
Escreva ("Digite o preço:")
Leia (P)
S2<-Q*P
VT<-s2+VT
Ate Q=0
 Escreval("Valor Total:",VT)
 Escreval("Quantidade Total:",S1)

Fimalgoritmo