Algoritmo "Modalidade"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Rodrigo Piantino
// Autor(a)    : Ana Amélia E. de Araújo
// Data atual  : 22/03/2019
Var i : Inteiro



Inicio
Escreva("Digite a Idade:")
Leia(I)
Se (I>=5)e (I<=10)entao
Escreva("Infantil")
fimse
Se (I>=11) e (I<=17)entao
escreva("Juvenil)
fimse
se(I>=18)e(I<=25)entao
escreva("Adulto")entao
fimse
Se (I>=26)entao
escreva("Não participa de nenhum modalidade!")
fimse



Fimalgoritmo